# Generated by Django 3.1.7 on 2021-03-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210311_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids'), ('sport', 'Sports')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(choices=[('t-shirt', 'T-Shirt'), ('shirt', 'Shirt'), ('jeans', 'Jeans'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('bike', 'Bike'), ('weights', 'Weights')], max_length=255, unique=True),
        ),
    ]
